apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: elosimulator
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: prefix
        backend:
          serviceName: backend
          servicePort: 8080
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80