apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: elosimulator
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        pathType: Prefix
        backend:
          serviceName: backend
          servicePort: 8080
      - path: /
        pathType: Exact
        backend:
          serviceName: frontend
          servicePort: 80