apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: elosimulator
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ajhaa/elosimulator
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP