apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- ingress.yaml
- service.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: ajhaa/elosimulator
  newTag: a95735b6fe427f0f9cdb04b95f5ef634e7cc4eea
