apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: elosimulator
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: IMAGE_PLACEHOLDER
        ports:
        - name: http
          containerPort: 80
          protocol: TCP