apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: ajhaa/elosimulator-front
  newTag: 7eb64f3399aa86bb5f56c4eb6a000e2b38a6f573
