# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - backend/**
      - .github/workflows/backend.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/
        
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
  
    - uses: actions/checkout@v2
      
    - name: Run tests
      run: go test -v ./...

  build:
    name: build backend
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: COMMIT_SHA=${{ github.sha }}
        tags: ajhaa/elosimulator:${{ github.sha }}
        file: backend/Dockerfile
        context: backend/

  deploy:
    name: deploy backend
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: deploy/backend/

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      run: |-
        ./kustomize edit set image IMAGE_PLACEHOLDER=ajhaa/elosimulator:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: 'deploy/backend/kustomization.yaml'
        message: New version release for gitops-app ${{ github.sha }}
